import type { RepositorySummary } from './api'

export const PHASE_1_NOW = new Date('2026-08-14T12:00:00Z')

export const phase1Repositories: RepositorySummary[] = [
  {
    id: 101,
    owner: 'erland',
    name: 'roman-alpha',
    fullName: 'erland/roman-alpha',
    url: 'https://github.com/erland/roman-alpha',
    visibility: 'PRIVATE',
    archived: false,
    fork: false,
    defaultBranch: 'main',
    topics: ['novel', 'publishing'],
    languages: ['Markdown', 'Python'],
    primaryLanguage: 'Python',
    license: { analysisState: 'COMPLETE', presence: 'PRESENT', recognized: true, key: 'mit', name: 'MIT License' },
    githubActions: { analysisState: 'COMPLETE', workflowsPresent: true, workflowCount: 2 },
    release: {
      analysisState: 'COMPLETE',
      releasePresent: true,
      latestReleaseName: 'v1.0.0',
      latestReleaseTag: 'v1.0.0',
      latestReleaseDate: '2026-08-10T10:00:00Z',
      latestReleasePrerelease: false,
    },
    activity: { pushedAt: '2026-08-13T10:00:00Z', updatedAt: '2026-08-13T11:00:00Z' },
    refreshStatus: { state: 'COMPLETE', message: 'Repository enrichment complete.' },
  },
  {
    id: 102,
    owner: 'erland',
    name: 'roman-beta',
    fullName: 'erland/roman-beta',
    url: 'https://github.com/erland/roman-beta',
    visibility: 'PRIVATE',
    archived: false,
    fork: false,
    defaultBranch: 'main',
    topics: ['novel'],
    languages: ['Java', 'Markdown'],
    primaryLanguage: 'Java',
    license: { analysisState: 'COMPLETE', presence: 'MISSING', recognized: false, key: null, name: null },
    githubActions: { analysisState: 'COMPLETE', workflowsPresent: false, workflowCount: 0 },
    release: {
      analysisState: 'COMPLETE',
      releasePresent: false,
      latestReleaseName: null,
      latestReleaseTag: null,
      latestReleaseDate: null,
      latestReleasePrerelease: null,
    },
    activity: { pushedAt: '2026-08-01T10:00:00Z', updatedAt: '2026-08-01T11:00:00Z' },
    refreshStatus: { state: 'COMPLETE', message: 'Repository enrichment complete.' },
  },
  {
    id: 103,
    owner: 'erland',
    name: 'tool-java',
    fullName: 'erland/tool-java',
    url: 'https://github.com/erland/tool-java',
    visibility: 'PUBLIC',
    archived: false,
    fork: false,
    defaultBranch: 'main',
    topics: ['developer-tool'],
    languages: ['Java', 'TypeScript'],
    primaryLanguage: 'Java',
    license: { analysisState: 'COMPLETE', presence: 'PRESENT', recognized: true, key: 'apache-2.0', name: 'Apache License 2.0' },
    githubActions: { analysisState: 'COMPLETE', workflowsPresent: true, workflowCount: 1 },
    release: {
      analysisState: 'COMPLETE',
      releasePresent: false,
      latestReleaseName: null,
      latestReleaseTag: null,
      latestReleaseDate: null,
      latestReleasePrerelease: null,
    },
    activity: { pushedAt: '2026-08-12T10:00:00Z', updatedAt: '2026-08-12T10:30:00Z' },
    refreshStatus: { state: 'COMPLETE', message: 'Repository enrichment complete.' },
  },
  {
    id: 104,
    owner: 'erland',
    name: 'legacy-archive',
    fullName: 'erland/legacy-archive',
    url: 'https://github.com/erland/legacy-archive',
    visibility: 'PRIVATE',
    archived: true,
    fork: false,
    defaultBranch: 'master',
    topics: [],
    languages: ['JavaScript'],
    primaryLanguage: 'JavaScript',
    license: { analysisState: 'COMPLETE', presence: 'MISSING', recognized: false, key: null, name: null },
    githubActions: { analysisState: 'COMPLETE', workflowsPresent: false, workflowCount: 0 },
    release: {
      analysisState: 'COMPLETE',
      releasePresent: true,
      latestReleaseName: 'legacy',
      latestReleaseTag: 'v0.9.0',
      latestReleaseDate: '2024-01-01T10:00:00Z',
      latestReleasePrerelease: false,
    },
    activity: { pushedAt: '2024-01-01T10:00:00Z', updatedAt: '2024-01-01T10:00:00Z' },
    refreshStatus: { state: 'COMPLETE', message: 'Repository enrichment complete.' },
  },
]
